USE [master]
GO

/****** Object:  Database [Usuarios]    Script Date: 24/03/2024 5:40:47 p. m. ******/
CREATE DATABASE [Usuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Usuarios', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Usuarios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Usuarios_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Usuarios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Usuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Usuarios] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Usuarios] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Usuarios] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Usuarios] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Usuarios] SET ARITHABORT OFF 
GO

ALTER DATABASE [Usuarios] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Usuarios] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Usuarios] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Usuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Usuarios] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Usuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Usuarios] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Usuarios] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Usuarios] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Usuarios] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Usuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Usuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Usuarios] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Usuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Usuarios] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Usuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Usuarios] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Usuarios] SET RECOVERY FULL 
GO

ALTER DATABASE [Usuarios] SET  MULTI_USER 
GO

ALTER DATABASE [Usuarios] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Usuarios] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Usuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Usuarios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Usuarios] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Usuarios] SET QUERY_STORE = OFF
GO

USE [Usuarios]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Usuarios] SET  READ_WRITE 
GO

USE [Usuarios]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 24/03/2024 5:40:57 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuario](
	[Id] [varchar](50) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Cedula] [int] NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pp_listar]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT * FROM Usuario;
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pp_obtener](@id varchar(50))
AS
BEGIN
	SET NOCOUNT ON;

	SELECT * FROM Usuario
	WHERE Id = @id;
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[pp_registrar]
(
	@id varchar(50),
	@nombre varchar(50),
	@cedula int,
	@telefono varchar(50),
	@direccion varchar(50),
	@email varchar(50)
)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Usuario
	(
		Id,
		Nombre,
		Cedula,
		Telefono,
		Direccion,
		Email
	)
	VALUES
	(
		@id,
		@nombre,
		@cedula,
		@telefono,
		@direccion,
		@email
	)
END
GO